### PR TITLE
refactored

### PR DESCRIPTION
**Pull request by sauloal**
Refactored following our new standards.

All containrs were successfully built and run except for the ones containing a GUI 

Someone who knows the packages should add the tests.

### CODE REVIEW

**Comment by Leprevost** [comment]
Hi Saulo, I just want to clarify some points before merging;

* In my opinion, the # File Author / Maintainer tag should be the last thing on the Dockerfile, If more than one author changes the file, there will be several names on that tag, and this can make the file more polluted. Also, it breaks the logical reasoning of the recipe, since it is not a functional tag.

* The containers that relies on GUIs still have problems to run, but fortunately, some of the collaborators here are the ones responsible for those software development, so maybe they can help us dealing with those problems.

* The Rstudio image was cloned from the [Rocker](https://github.com/rocker-org) repository, they also use their own base image, so if we change that for our image, the containers breaks, I tested before.

**Comment by sauloal** [comment]
> Hi Saulo, I just want to clarify some points before merging;
> 
> In my opinion, the # File Author / Maintainer tag should be the last thing on the Dockerfile, If more > than one author changes the file, there will be several names on that tag, and this can make the > file more polluted. Also, it breaks the logical reasoning of the recipe, since it is not a functional tag.
It's a matter of preference. I don't have a really strong feeling about it but I think that the author's name is part of the header of documents in general. But I can change it. not problem. 
And, indeed, it comes after the FROM tag which is a functional tag.
I will try to change it tonight and pull again.

> The containers that relies on GUIs still have problems to run, but fortunately, some of the collaborators here are the ones responsible for those software development, so maybe they can help us dealing with those problems.
Ok. To reiterate, they are compiling, I'm just not able to connect to the X11 session

> The Rstudio image was cloned from the Rocker repository, they also use their own base image, so if we change that for our image, the containers breaks, I tested before.
I Didn't change the base image for the Rstudio. It is crashing when calling a boost library when compiling one of the R packages.

**Comment by sauloal** [comment]
@Leprevost . ive moved the maintainer statement to the end

**Comment by Leprevost** [comment]
thanks, There are conflicts for the merging, I have to review them manually before merging.

**Comment by sauloal** [comment]
@Leprevost  @ypriverol 
should we merge?

**Pull request merged**
